### ISSUE TITLE
SR-IOV CNI to properly restore the state of a VF

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-cni#115]
### What happened?

SR-IOV CNI does not restore the state of a VF to its original value in case:

1. Failure mid way during cmdAdd call
2. cmdDel call

During cmdDel SR-IOV CNI restores some VF parameters implicitly to a hardcoded predefined value
for: `spoofchk`, `vf trust`, `vf rate`

Failure to properly restore the state may lead to future cmdAdd operations to fail as described by:
#113 #114 

### What did you expect to happen?

VF state is restored to its original value. That is to the state that preceded the last cmdAdd operation.

### What are the minimal steps needed to reproduce the bug?

invoke CNI when the initial state of the VFs in the system differs from  what is depicted in [ResetVfConfig()](https://github.com/intel/sriov-cni/blame/aa76bad2844a552d9290b7264b76fd2a533606e8/pkg/sriov/sriov.go#L409)

### Anything else we need to know?

In my opinion the approach should be:

1. Clean whatever was configured during cmdAdd in case of a failure Or Cache the partial configuration state in case of failure for cleanup (when using K8s + Multus it calls cmdDel even if cmdAdd fails from what i saw but CNI spec does not impose any restrictions on the caller in regards to calling cmdDel even if cmdAdd fails)
2. Clean as much stuff as possible in cmdDel, today it exits on first failure
3. The definition of cleanup should be to restore the system to its original state.

**Comment by killianmuldoon** [comment]
Can this be closed ?

**Comment by adrianchiris** [comment]
PR #114 took care of restoring a VF to its original state during cmdDel, assuming the previous cmdAdd command completed successfully and managed to save its configuration.

There are additional steps required:
1. Clean whatever was configured during cmdAdd in case of a failure
2. Clean as much stuff as possible in cmdDel, today it exits on first failure

the meaning of cleaning is restoring the system to its original state.

**Comment by zshi-redhat** [comment]
This issue was discussed in Monday's resource management meeting.
The idea is to review the code and improve the VF state restore in cmdAdd/cmdDel where necessary.

**Comment by SchSeba** [comment]
closing this one as https://github.com/k8snetworkplumbingwg/sriov-cni/pull/222 is merged now feel free to reopen if needed
