### ISSUE TITLE
Wrong MAC address value returned in Result on CmdAdd

### ISSUE THREAD

**Issue by DmytroLinkin** [k8snetworkplumbingwg/sriov-cni#143]
### What happened?
MAC address returned in Result is the same as initial MAC address value of the VF, disregarding whether it was passed in cni conf or not.

### What did you expect to happen?
Expected it to be equal to the one passed in cni conf.

### What are the minimal steps needed to reproduce the bug?
Use cnitool utility:
```
$ ./cnitool add sriov-network /var/run/netns/s-dev
{
    "cniVersion": "0.4.0",
    "interfaces": [
        {
            "name": "eth0",
            "mac": "56:0a:69:b3:a6:5b",
            "sandbox": "/var/run/netns/s-dev"
        }
    ],
    "ips": [
        {
            "version": "4",
            "interface": 0,
            "address": "10.56.217.2/24",
            "gateway": "10.56.217.1"
        }
    ],
    "routes": [
        {
            "dst": "0.0.0.0/0"
        }
    ],
    "dns": {}
}
$ ip netns exec s-dev ip link
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
105: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether e4:11:22:33:44:55 brd ff:ff:ff:ff:ff:ff
```

### Anything else we need to know?
In the code I see that mac address value, returned by SetupVF function, assigned from the `linkObj` after mac address was setted. That's not correct, since `linkObj` don't point directly to underlying kernel's netlink object, so mac address still has initial value.
NIC used: Mellanox ConnectX-5

### Component Versions
Please fill in the below table with the version numbers of applicable components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV CNI Plugin            |master|
|Multus                       |master|
|SR-IOV Network Device Plugin |master|
|Kubernetes                   |v1.19.2| 
|OS                           |CentOS 7.8|

### Config Files
Config file locations may be config dependent.
```
$ cat 20-sriov-cni.conf
{
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "type": "sriov",
  "deviceID": "0000:82:02.3",
  "MAC": "e4:11:22:33:44:55",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}
```

**Comment by martinkennelly** [comment]
I am seeing this issue intermittently, in fact it seems to occur rarely on my VFs. I saw it consistently on one VF, but following reset of VFs, it disappeared. Are you seeing consistent failures?
 

You're correct about linkObj. I tested it there. Testing your follow up patch now. Thank you for this!

**Comment by DmytroLinkin** [comment]
> I am seeing this issue intermittently, in fact it seems to occur rarely on my VFs. 

Do You set MAC with cni config? Issue happens when MAC is specified.
> I saw it consistently on one VF, but following reset of VFs, it disappeared.

Yes, reset return settings back to the normal. But the problem might occur if some{one,thing} will rely on cmdAdd results.
> Are you seeing consistent failures?

Frankly speaking, I didn't have any real failures with this. Bumped into it, when saw the Result and MAC looked suspicious for me. But as I mentioned, specifying MAC address in config triggers it.

**Comment by martinkennelly** [comment]
> > I am seeing this issue intermittently, in fact it seems to occur rarely on my VFs.
> 
> Do You set MAC with cni config? Issue happens when MAC is specified.

Yes. I still only see it very rarely, but I did see it.
> > I saw it consistently on one VF, but following reset of VFs, it disappeared.
> 
> Yes, reset return settings back to the normal. But the problem might occur if some{one,thing} will rely on cmdAdd results.

Correct. 
> > Are you seeing consistent failures?
> 
> Frankly speaking, I didn't have any real failures with this. Bumped into it, when saw the Result and MAC looked suspicious for me. But as I mentioned, specifying MAC address in config triggers it.

I see. It occurs rarely for me. So you are seeing it consistently when MAC defined?

**Comment by DmytroLinkin** [comment]
> I see. It occurs rarely for me. So you are seeing it consistently when MAC defined?

Didn't paid many attention what's returned by the plugin on real runtime, but with cnitool issue persistant.

**Comment by adrianchiris** [comment]
Based on the fix id expect it to happen consistently when a different MAC is specified for VF regardless of who invokes the CNI

**Comment by martinkennelly** [comment]
> Based on the fix id expect it to happen consistently when a different MAC is specified for VF regardless of who invokes the CNI

Yeah, this is why I am wondering why I am not seeing it consistently with cnitool when a different MAC is specified.

**Comment by adrianchiris** [comment]
I will create a setup and look at it, will update.

**Comment by adrianchiris** [comment]
Update: reproducing consistently when invoking the CNI with cnitool.
and is fixed with the PR @DmytroLinkin proposed.

>  I saw it consistently on one VF, but following reset of VFs, it disappeared.

when Resetting VFs (i assume you recreate them via sysfs) make sure to also reset the VF's administrative MAC on the PF.
if it remains set then when the VF is created, it will get the administrative MAC value.
