### ISSUE TITLE
make clean fails: "rm: cannot remove"

### ISSUE THREAD

**Issue by amorenoz** [k8snetworkplumbingwg/sriov-cni#151]
### What happened?
sriov-cni cannot be cleaned properly, running `make clean` yields a bunch of:

`rm: cannot remove 'sriov-cni/.gopath/pkg/mod/github.com/containernetworking/cni@v0.8.0/logo.png': Permission denied`

### What did you expect to happen?
make clean should work
### What are the minimal steps needed to reproduce the bug?
`
git clone https://github.com/k8snetworkplumbingwg/sriov-cni.git && cd sriov-cni && make && make clean
`
### Anything else we need to know?
Due to recent move to go.mod

**Comment by martinkennelly** [comment]
Confirmed.
