### ISSUE TITLE
Travis-ci.org is shut down now

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/sriov-cni#184]
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Travis is transitioning to a new .com domain and the old .org version is being shut down. This caught me off-guard.
There are new requirements it seems for OSS using travis for free. See curl issue https://github.com/curl/curl/issues/7150

I do not think its worthwhile applying for OSS status given what I have read in the curl issue above. Looking for inputs here.
We currently depend on travis for building and pushing docker images to nfvpe/sriov-cni.

Do we want to continue supporting nfvpe and if so, can we replace this with a GH action?

**Comment by zshi-redhat** [comment]
I think it's the time to switch from nfvpe to ghcr.io.

**Comment by martinkennelly** [comment]
Agreed - I want to signal this to consumers on docker. Who can I contact to hopefully add a note to https://hub.docker.com/r/nfvpe/sriov-cni ? Doug S?

**Comment by zshi-redhat** [comment]
> Agreed - I want to signal this to consumers on docker. Who can I contact to hopefully add a note to https://hub.docker.com/r/nfvpe/sriov-cni ? Doug S?

I can add a note in the link above.
