### ISSUE TITLE
Consider updating beta.kubernetes.io/arch to kubernetes.io/arch

### ISSUE THREAD

**Issue by MichalGuzieniuk** [k8snetworkplumbingwg/sriov-cni#193]
## What would you like to be added?
Consider updating beta.kubernetes.io/arch to kubernetes.io/arch inside the example daemonset to keep documentation up to data.

https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/images/k8s-v1.16/sriov-cni-daemonset.yaml

## What is the use case for this feature / enhancement?
The **beta.kubernetes.io/arch** is deprecated since Kubernetes version 1.14 and are targeted for removal in v1.18 

As I see this change was merged on K8s side within this pull request https://github.com/kubernetes/kubernetes/pull/89462 to v1.19

**Comment by zshi-redhat** [comment]
@MichalGuzieniuk thanks for capturing the change!
Would you mind send a PR updating the nodeSelector labels?

**Comment by MichalGuzieniuk** [comment]
@zshi-redhat sure, I will provide a PR for that issue.
