### ISSUE TITLE
Enhance debugging for SRIOV

### ISSUE THREAD

**Issue by sandeep-robin** [k8snetworkplumbingwg/sriov-cni#207]
## What would you like to be added?

Need more debug logs for request and response for cmdAdd and while calling device plugin
## What is the use case for this feature / enhancement?
helps in understanding what vf is assigned and what is request passed to CNI during cmdAdd or cmdDel

**Comment by SchSeba** [comment]
Hi @sandeep-robin thanks for opening the issue!

the CNI runs when multus is calling it, does changing multus logs to debug give you enough information?
https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/configuration.md
