### ISSUE TITLE
VF configs are not reset when SetupVF fails

### ISSUE THREAD

**Issue by joelcheison** [k8snetworkplumbingwg/sriov-cni#212]
What happened?

In a scenario where a VF setup setup fails (SetupVF method), the VF will not be reset to its original configuration by sriov-cni. The VF will only be moved from pod namespace to default namespace by the ReleaseVF method. The ResetVF method is not called in the error hander function. 

If the VF had been configured using the extended configuration parameter of the sriov-cni NAD, then the above behavior will leave the VF with the with the NAD configurations and sriov-cni will not reset the VF to the OrigVfState.

One could argue that the, if the failure occurs, and then the pod gets deleted, the cmdDel will take care of resetting the VF. But, cmdDel expects the cache config to be present in /var/lib/cni to know the OrigVfState. The data caching is one of the last steps in cmdAdd much later than the call to SetupVf. So if SetupVF fails, the code exits before caching the data. Now cmdDel needs the cached data as its first step. The cache is not available and cmdDel fails with the following error. 

_**2022-05-09T15:42:42+02:00 [error] delegateDel: error invoking DelegateDel - "sriov": error in getting result from DelNetwork: error reading cached NetConf in /var/lib/cni/sriov with name 2ff55d47c1452a72384df6aa49f0a80aa52d37295b6bef40385b5342940c83
2022-05-09T15:42:42+02:00 [error] error in getting result from DelNetwork: error reading cached NetConf in /var/lib/cni/sriov with name 2ff55d47c1452a72384df6aa49f0a80aa52d37295b6bef40385b5342940c834e-net4**_

The VF remains with the config and does not get reset to its Original state before sriov-cni took over.

### What did you expect to happen?
sriov-cni even during a VF setup failure should leave the the VF in its original configurations

### What are the minimal steps needed to reproduce the bug?
Build an sriov-cni binary with a forced error in the SetupVF function.
Use a NAD with extended configurations like (vlan, spoofcheck, trustmode etc). Create a pod using the NAD. Once the pod fails, the VF will still have configs from the NAD, and not its original state.

### Anything else we need to know?

An easy fix will be to call the ResetVF function along with the ReleaseVF function in the error handler (deferred function) in the cmdAdd function within main.go

Like so:

[Patch_no_vf_reset_on_failure.diff.txt](https://github.com/k8snetworkplumbingwg/sriov-cni/files/9138668/Patch_no_vf_reset_on_failure.diff.txt)

### Component Versions
Please fill in the below table with the version numbers of applicable components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV CNI Plugin            |v2.6|
|Multus                       |v3.7.2|
|SR-IOV Network Device Plugin |v3.3.2|
|Kubernetes                   |1.23.3| 
|OS                           |Linux|

### Config Files
Config file locations may be config dependent.

##### CNI config (Try '/etc/cni/net.d/')
NIL
##### Device pool config file location (Try '/etc/pcidp/config.json')
NIL
##### Multus config (Try '/etc/cni/multus/net.d')
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"portMappings": true, "bandwidth": true}, "logLevel": "verbose", "logFile": "/var/log/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.1", "plugins": [ { "type": "calico", "log_level": "info", "log_file_path": "/var/log/calico/cni/cni.log", "datastore_type": "kubernetes", "nodename": "cp-bm25c2", "mtu": 2000, "ipam": { "type": "calico-ipam" }, "policy": { "type": "k8s" }, "kubernetes": { "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "portmap", "snat": true, "capabilities": {"portMappings": true} }, { "type": "bandwidth", "capabilities": {"bandwidth": true} }, { "type": "tuning", "sysctl": {"net.ipv4.tcp_mtu_probing": "1"} } ] } ] }

##### Kubernetes deployment type ( Bare Metal, Kubeadm etc.)
Bare-Metal using CAPI + Metal3

**Comment by joelcheison** [comment]
diff --git a/cmd/sriov/main.go b/cmd/sriov/main.go
index 12e5925..4a9c2e4 100644
--- a/cmd/sriov/main.go
+++ b/cmd/sriov/main.go
@@ -94,6 +98,8 @@ func cmdAdd(args *skel.CmdArgs) error {
 				})
 				if err == nil {
 					_ = sm.ReleaseVF(netConf, args.IfName, args.ContainerID, netns)
+					// Reset the VF if failure occurs before the netconf is cached
+					_ = sm.ResetVFConfig(netConf)**
 				}
 			}
 		}()

**Comment by adrianchiris** [comment]
i believe this relates to: 

https://github.com/k8snetworkplumbingwg/sriov-cni/issues/115

**Comment by SchSeba** [comment]
closing this one as https://github.com/k8snetworkplumbingwg/sriov-cni/pull/222 is merged now feel free to reopen if that doesn't fix the issue
