### ISSUE TITLE
VF stuck in \"device or resource busy\" while using sriov-cni extended configurations

### ISSUE THREAD

**Issue by joelcheison** [k8snetworkplumbingwg/sriov-cni#213]
### What happened?
While using sriov-cni with a NAD that has extended configurations (vlan, spoofcheck, trust-mode etc), the pods fail to come up.
From the /var/log/messages we could see errors like below:

_Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "539d9217f6b46b2450f8b3e1bf2b0c8a09d5d89ca80fd61d050124dac39be488": plugin type="multus" name="multus-cni-network" failed (add): [default/cnis-2221-cnis-2221-v1:cnis-2221-right-2-cnis-2221-v1]: error adding container to network "cnis-2221-right-2-cnis-2221-v1": failed to set up pod interface "net4" from the device "enp134s0f1": error setting up interface in container namespace: **"error bringing interface up in container ns: \"device or resource busy\"**"_ 

### What did you expect to happen?
The pod to come up with the VF attached.

### What are the minimal steps needed to reproduce the bug?
Not Easy to reproduce.
Creating a k8s Deployment with a replica count of 15-20, all consuming VFs from the same PF

### Anything else we need to know?
From looking at the code I feel that this could potentially be a timing issue but I am not sure of this. 
In the cmdAdd method, the ApplyVFConfig method that applies the extended VF config is using the netlink golang module. Netlink uses unix domain sockets underneath to finally configure the VF. Right after the ApplyVFConfig is called the sriov-cni code tries to move the the VF to the pod's network namespace, and that is when the code complains that the device is busy.

I am not sure if the netlink code setting the configs on the VF is synchronous or not. Maybe it is asynchronous and returns after posting a request to apply the VF config and then when sriov-cni tries to move the VF into the pod namespace the configs are still being applied.

All the info above are inferred data from experiments and not from deep understanding of the sriov-cni nor netlink source codes.

Why I feel that this is a timing issue is because when I introduced a 500ms sleep between ApplyVFConfig and the namespace change, the issue was no longer seen.

Patch:

[Patch_delay_resource_busy.diff.txt](https://github.com/k8snetworkplumbingwg/sriov-cni/files/9138675/Patch_delay_resource_busy.diff.txt)

### Component Versions
Please fill in the below table with the version numbers of applicable components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV CNI Plugin            |v2.6|
|Multus                       |v3.7.2|
|SR-IOV Network Device Plugin |v3.3.2|
|Kubernetes                   |1.23.3| 
|OS                           |Linux|

### Config Files
Config file locations may be config dependent.
NIL
##### CNI config (Try '/etc/cni/net.d/')
NIL
##### Device pool config file location (Try '/etc/pcidp/config.json')
NIL

##### Multus config (Try '/etc/cni/multus/net.d')
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"portMappings": true, "bandwidth": true}, "logLevel": "verbose", "logFile": "/var/log/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.1", "plugins": [ { "type": "calico", "log_level": "info", "log_file_path": "/var/log/calico/cni/cni.log", "datastore_type": "kubernetes", "nodename": "cp-bm25c2", "mtu": 2000, "ipam": { "type": "calico-ipam" }, "policy": { "type": "k8s" }, "kubernetes": { "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "portmap", "snat": true, "capabilities": {"portMappings": true} }, { "type": "bandwidth", "capabilities": {"bandwidth": true} }, { "type": "tuning", "sysctl": {"net.ipv4.tcp_mtu_probing": "1"} } ] } ] }

##### Kubernetes deployment type ( Bare Metal, Kubeadm etc.)
Bare-Metal using CAPI + Metal3

**Comment by adilGhaffarDev** [comment]
I have a question regarding this issue, can we add check if device or resource is busy we add wait and retry for few times and if keeps in that state we return error else continue with remaining run.

**Comment by SchSeba** [comment]
@adilGhaffarDev why we need to retry?
if we didn't manage to configure we will return an error and multus will call the cni again.

I don't think is a good idea to add retries to the sriov itself, if we have retry here we will not return an error to multus so it will be super hard in the future to understand why the sriov-cni is still running after some time.

**Comment by adilGhaffarDev** [comment]
Agree with @SchSeba . We can close this issue.
/close
