### ISSUE TITLE
PCI Address to NAD mapping

### ISSUE THREAD

**Issue by joelcheison** [k8snetworkplumbingwg/sriov-cni#215]
In cases with pods having more than one container that needs SRIOV/DPDK devices, there is no way currently to select which device on which container to assign the configurations on the NAD to.

[sandbox-multicontainer.txt](https://github.com/k8snetworkplumbingwg/sriov-cni/files/9178730/sandbox-multicontainer.txt)

The above POD has 4 NADs:
bgf-media-dpdk-net
bgf-media-dpdk-net-right
bgf-int-dpdk-net
bgf-int-dpdk-net-right

Also 2 containers **dpdk1** and **dpdk2**, that has 1 device of resource type **intel.com/intel_sriov_dpdk_left** and 1 device of type **intel.com/intel_sriov_dpdk_right** each.

The requirement is:

on dpdk1:
bgf-media-dpdk-net   ----> intel.com/intel_sriov_dpdk_left
bgf-media-dpdk-net-right  -----> intel.com/intel_sriov_dpdk_right

on dpdk2:
bgf-int-dpdk-net   ----> intel.com/intel_sriov_dpdk_left
bgf-int-dpdk-net-right  -----> intel.com/intel_sriov_dpdk_right

But the order is not always ensured. The NAD with the right postfix could be applied to the  could be applied to intel.com/intel_sriov_dpdk_left device . Is there a way to map a particular NAD to a device PCI address.

We tried using the **deviceID** field in in the sriov-cni extended configurations:
https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/docs/configuration-reference.md

This field had no effect in choosing the device. What is the right wat to use the deviceID field?
Is there an existing way to map a NAD to a PCI device, or are there plans to integrate such behavior in the community?

**Comment by adrianchiris** [comment]
IIUC, knowing network to device mapping would solve your problem.

are you familiar with device-info-spec ? [1] , see example of annotation exposed by multus [2]

[1] https://github.com/k8snetworkplumbingwg/device-info-spec/blob/main/SPEC.md
[2] https://github.com/k8snetworkplumbingwg/device-info-spec/blob/main/SPEC.md#612-example

**Comment by SchSeba** [comment]
closing this issue
