### ISSUE TITLE
Multus-cni is not supported in Azure even if Azure Managed K8S as well

### ISSUE THREAD

**Issue by subratust** [k8snetworkplumbingwg/sriov-cni#218]
Tried install k8s on the top of the Azure vm enabled with Accelerated Network (Mellnox) .Checked with Microsoft Azure team ,as per them Multus CNI is not supported in Azure even if Azure Managed K8S as well .But which works for AWS .Could you please verify from your end or Help me out to setup on Azure vm .

**Comment by SchSeba** [comment]
Hi @subratust sorry I don't understand the request there.

**Comment by SchSeba** [comment]
no updates in 29 days closing this issue please feel free to reopen if needed
