### ISSUE TITLE
Can this plugin be used with Docker containers? If Yes, please point to the documentation.

### ISSUE THREAD

**Issue by sumitk31** [k8snetworkplumbingwg/sriov-cni#224]
## Do you have a proposed response or remediation for the issue?

**Comment by SchSeba** [comment]
Hi @sumitk31 I never try something like that so I don't know. This CNI plugin is to be used as a secondary nic in k8s by multus-cni

**Comment by SchSeba** [comment]
closing this issue feel free to reopen if needed
