### ISSUE TITLE
with DPDK userspace driver config, how to attach the dummy interface inside the container

### ISSUE THREAD

**Issue by ankush06** [k8snetworkplumbingwg/sriov-cni#225]
hi,

I am looking for a configuration to attach a dummy interface inside a container and assign the allocated IP.
This is required for an app to bound to an interface. 

If   DPDK userspace driver config does not attach a interface inside a container, then how the app is actually going to make use of it?

Sorry, i am new to SRIOV and DPDK domain, so these questions may sound silly. Any reference to this will be very helpful for me.

Thanks

**Comment by SchSeba** [comment]
Hi @ankush06 please check the https://doc.dpdk.org/guides/

in general DPDK use user-space drivers to bypass the kernel networking

**Comment by SchSeba** [comment]
closing this issue feel free to reopen if needed
