### ISSUE TITLE
go versrion 1.19  bulid error 

### ISSUE THREAD

**Issue by flyfish002** [k8snetworkplumbingwg/sriov-cni#229]
os:   Ubuntu 20.04.5 LTS \n \l
kernel:   5.4.0-128-generic
go version:     go1.19

cd sriov-cni/
make  

* can't run linter goanalysis_metalinter: goanalysis_metalinter: buildir: package "atomic" (isInitialPkg: false, needAnalyzeSource: true): T

**Comment by zeeke** [comment]
hi @flyfish002, thank you for reporting.
can you post the full `make` command output?

also, can you try upgrading golangci version to 1.49:
- check current version with `./bin/golangci-lint --version` (should be 1.45)
- edit Makefile [here](https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/Makefile#L66) with
```
	$Q go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45
```
- then
```
rm ./bin./golangci-lint
make
```

**Comment by SchSeba** [comment]
Hi @flyfish002 any update on this issue or we can close it?

**Comment by adrianchiris** [comment]
as there are no updates on this issue and sriov-cni is now on go 1.20 , golang CI on 1.52.1 im closing this one.
(CI is working fine + build/lint/test on my local setup)

please reopen with  updated inputs if issue re-occurs.
