### ISSUE TITLE
Request: publish a new release

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/sriov-cni#230]
## What would you like to be added?

Hi teams! Four months have passed since the last release, during which we had the following two major PRs:

- [Send IPv4 GARP and IPv6 Unsolicited NA in "cmdAdd"](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/216)
- [bump golang to 1.19](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/228) && [bump netlink&cni version and support add ecmp route](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/227)
- [Add pci address lock for allocated devices](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/220) (close to merged)
- [Reset the VF if failure occurs before the netconf is cached](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/222)(close to merged)

I think it makes sense to publish a new release at this time, especially to support adding ECMP routes, please see #227 

How do you think?  I would really appreciate it if you guys replied to me. Thanks!

**Comment by cyclinder** [comment]
@adrianchiris

**Comment by adrianchiris** [comment]
+1

should we also try to add PRs #220 and #222 as well for the release ? (i think yes)

@SchSeba  @Eoghan1232 thoughts ?

**Comment by adilGhaffarDev** [comment]
Unit tests were failing in #222 now its resolved. Kindly check.

**Comment by SchSeba** [comment]
+1

**Comment by adrianchiris** [comment]
After discussion in community meeting on Nov 15, it was agreed have a release of sriov CNI.

In addition, the following PRs should also be part of the release:

 #220 
#222

**Comment by cyclinder** [comment]
Hi @adilGhaffarDev , Both of the above PRs have been merged, is it time to new a release?  :)

**Comment by adilGhaffarDev** [comment]
> Hi @adilGhaffarDev , Both of the above PRs have been merged, is it time to new a release? :)

Thank you for merging my PR, I don't have anything else that needs to be merged from my side, so ok for me. 👍🏽

**Comment by cyclinder** [comment]
hahah... I'm so sorry, Your name and @adrianchiris  are too similar, so I misread the name, I am very sorry and thank you for your reply 😂

**Comment by Eoghan1232** [comment]
both PR's are now merged.
@adrianchiris think we are good to go on next release?

**Comment by adrianchiris** [comment]
id like to get PR #232 in as well. it has been reviewed, pending CI job to pass.

stay tuned for release.

**Comment by adrianchiris** [comment]
> both PR's are now merged.
> @adrianchiris think we are good to go on next release?

was planning to wait for CI to pass on the PR.  lets wait for Mellanox CI job to complete before release.

**Comment by adrianchiris** [comment]
v2.7.0 has been released !
