### ISSUE TITLE
Multidevice network ordering and network to device mapping not clearly documented.

### ISSUE THREAD

**Issue by joelcheison** [k8snetworkplumbingwg/sriov-cni#231]
Hi,

When it comes to multiple VF resources and pods with multiple containers, there is not a clear documentation of how the network-definitions are applied onto the resources.

Even with the use of the device-info spec annotation[k8s.v1.cni.cncf.io/resourceName] on the NAD the mapping can get confusing.

Example:

If the requirement is to have a pod with 2 containers and both containers get 2 VFs from the resource intel_sriov. One of the VF in each container should be configured according to a network called sriov-vlan100, and the other needs to be configured using sriov-vlan200.

Pod definition:

apiVersion: v1
kind: Pod
  metadata:
    annotations:
       k8s.v1.cni.cncf.io/networks: **sriov-vlan100, sriov-vlan100, sriov-vlan200, sriov-vlan200**
  spec:
     containers:
     - name: sriov-container1
       resources:
         requests:
           intel.com/intel_sriov:2
         limits:
           intel.com/intel_sriov:2
     - name: sriov-container2
       resources:
         requests:
           intel.com/intel_sriov:2
         limits:
           intel.com/intel_sriov:2
           
           
Such a a definition will cause both VFs in sriov-container1 to be configured with sriov-vlan100 and both VFs in sriov-container2 to be configured with sriov-vlan200

Whereas if the annotation was as shown below where the NADs are in alternating order, the requirement will be achieved.

    annotations:
       k8s.v1.cni.cncf.io/networks: sriov-vlan100, sriov-vlan200, sriov-vlan100, sriov-vlan200

This however is not documented in the README files, and there are no examples showing the use of multiple VF resources and multiple NADs in a single pod.

I figured this out through trial and error.

The situation gets more complex if there are more than one resource for the containers. Like "intel.com/intel_sriov_left" and "intel.com/intel_sriov_right"

The data under the requests/limits is a map and is unordered. Where the "k8s.v1.cni.cncf.io/networks" annotation is an ordered list.
In such cases, we can use the device-info-spec annotation on the NAD "k8s.v1.cni.cncf.io/resourceName", to bind the NAD to the correct resource. And then the "k8s.v1.cni.cncf.io/networks" pod annotation should also have networks in the correct order.

All these had to be found out through trial and error as they were not documented.

Please include in the documentation on how the NAD to device mapping works, and how the ordering of the pod annotation dictates the order in which the devices are configured. This will also aid in the users getting a deprecation warning if this behavior changes in the future.

Also more complex examples with more devices and multiples NADs will be helpful to users in understanding how to configure their networks in practical network plumbing scenarios.

**Comment by adrianchiris** [comment]
Greetings !

> Please include in the documentation on how the NAD to device mapping works, and how the ordering of the pod annotation dictates the order in which the devices are configured. This will also aid in the users getting a deprecation warning if this behavior changes in the future.

That seems to be related to the the caller of sriov-cni which provides a device ID to be used to set up the interface for the network. i.e in multus CNI.

there are some additional quirks with how things are working today, as networking is done at pod level (pod has network namespace which is shared by all containers) but resources are container level.

**Comment by SchSeba** [comment]
closing this one for housekeeping feel free to reopen if needed
