### ISSUE TITLE
Does sriov-cni still support Kubernetes 1.10-1.22?

### ISSUE THREAD

**Issue by s1061123** [k8snetworkplumbingwg/sriov-cni#235]
This is not a issue, just a question. Does sriov-cni still support Kubernetes 1.10-1.22?

Currently Kubernetes mentioned to maintain 1.25, 1.24 and 1.23, as supported version (see [Release page](https://kubernetes.io/releases/)), however in sr-iov `image` repo, there are still deployment yaml file for 1.10-1.15 and I just wonder whether sr-iov repo still supports these old version or not.

**Comment by SchSeba** [comment]
+1

**Comment by SchSeba** [comment]
https://github.com/k8snetworkplumbingwg/sriov-cni/commit/8ba97bbfa6e40b2d5bca04339f32b076865e48b8
