### ISSUE TITLE
GetPfName here uncorrectly, when enable representor interface

### ISSUE THREAD

**Issue by guoyaowen30** [k8snetworkplumbingwg/sriov-cni#247]
https://github.com/k8snetworkplumbingwg/sriov-cni/blob/0303583646f9def1feab7452f8aaea2150577f9f/pkg/config/config.go#L107
failed cause sort  by strings in Mellnox system, example, PF is eth2，and when we enable representor port ，now we have eth2, eth 8,eth9,eth10, after that, run GetPfName will return eth10.not eth2.

**Comment by SchSeba** [comment]
Hi @guoyaowen30 sriov-cni is only for legacy sriov mode.

the sriov-cni doesn't support switchdev mode. you will need a different CNI, for example I know ovn-kubernetes uses the sriov device plugin for hardware offloading with switchdev.

**Comment by adrianchiris** [comment]
there are a couple of secondary network CNI that support switchdev:

1. https://github.com/k8snetworkplumbingwg/ovs-cni
2. https://github.com/k8snetworkplumbingwg/accelerated-bridge-cni

and indeed ovn-kubernetes supports switchdev as well

**Comment by SchSeba** [comment]
feel free to reopen if needed
