### ISSUE TITLE
Question: differences from host-device plugin?

### ISSUE THREAD

**Issue by AlexHill** [k8snetworkplumbingwg/sriov-cni#249]
Just trying to sharpen my understanding here.

host-device CNI will happily attach a VF network interface to a pod, given the appropriate deviceID. SR-IOV CNI will not attach a PF, failing with `LoadConf(): failed to get VF information: "lstat /sys/bus/pci/devices/0000:41:00.1/physfn/net: no such file or directory"`.

SR-IOV Network Device Plugin, with certain configurations, will advertise PFs, in the same pool as VFs. So this is a bit of a foot-gun - you can create a heterogeneous pool of resources, but with no way to know which device you'll be allocated by the DP, you can't pick the right network. Obviously you can avoid this through careful configuration, but it's easy enough to run into.

SR-IOV CNI obviously offers a lot of extra parameters you can set over host-device, vlans etc - but which of those are exclusively applicable to VFs and not PFs? And in which other situations would host-device NOT work in place of sriov-cni? Could SR-IOV CNI be extended to support PFs as well, as a kind of supercharged host-device plugin, or would that violate some principle of its design?

**Comment by adrianchiris** [comment]
> SR-IOV CNI obviously offers a lot of extra parameters you can set over host-device, vlans etc - but which of those are exclusively applicable to VFs and not PFs?

most of the paremeters in sriov-cni config[1] are only applicable to VF (excluding IPAM)

> And in which other situations would host-device NOT work in place of sriov-cni?

in any case where you need to configure VF related parameters to setup network

> Could SR-IOV CNI be extended to support PFs as well, as a kind of supercharged host-device plugin, or would that violate some principle of its design?

I think we would want sriov-cni to handle SRIOV as it is today and not mix the two.

[1] https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/docs/configuration-reference.md#parameters

**Comment by SchSeba** [comment]
Hi @AlexHill if I rememeber the only variable in the DP that select PF is the PCIaddress so that will be the only way I think we can have a mixed pool.

the  PCIaddress was created in the device plugin to support virtual env where you run a k8s cluster on a VM and you pass VFs to that VM

**Comment by SchSeba** [comment]
closing this one @AlexHill feel free to reopen if needed
