### ISSUE TITLE
github workflow for static analysis to run lint using "make lint" command

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-cni#260]
## What would you like to be added?

we should modify our golangci job in static-scan.yml github workflow to just invoke `make lint` to avoid a split brain scenario
where Makefile points to one golangci-lint version and the workflow points  to another

## What is the use case for this feature / enhancement?
less things to update when bumping golangci-lint version

**Comment by adrianchiris** [comment]
#259

**Comment by SchSeba** [comment]
https://github.com/k8snetworkplumbingwg/sriov-cni/pull/265
