### ISSUE TITLE
sriov-cni build is not idempotent

### ISSUE THREAD

**Issue by jiriproX** [k8snetworkplumbingwg/sriov-cni#263]
When you run make second time then it fails:
make
Running gofmt...
Running golangci-lint...
make: *** No rule to make target '.gopath/pkg/mod/github.com/blizzy78/varnamelen@v0.8.0/testdata/src/falsenegativechanrecv/chanrecv', needed by '/opt/cek/sriov-cni/build/sriov'.  Stop.

### What did you expect to happen?
It should pass

### What are the minimal steps needed to reproduce the bug?
Run make and then run  make again.

### Anything else we need to know?
Issue is already fixed on upstream component https://github.com/blizzy78/varnamelen/pull/26

### Component Versions

Component | Version|
------------------------------|--------------------|
|SR-IOV CNI Plugin            |v2.7.0/master|

**Comment by zeeke** [comment]
The problems comes from a dependency that has a file with a whitespace
- https://github.com/blizzy78/varnamelen/pull/26

We can fix this by bumping the dependency, but I think it would be cleaner to simplify the build rule by removing the `$(GOFILES)` [dependency from the rule](https://github.com/k8snetworkplumbingwg/sriov-cni/blob/c1faa0805c92be6e5c629e9caf481f43cfee866c/Makefile#L58).

**Comment by jiriproX** [comment]
I know, I've proposed fix there. It is merged but they do not have official version tag with this fix yet. Yes, if that dependency is not needed any longer for srioc-cni then the removal will be better. When this fix will be ready? When can we expect new version with recent fixes?

**Comment by jiriproX** [comment]
@SchSeba @zeeke When is planned new version release? I would need fix for this issue in it.

**Comment by zeeke** [comment]
I think this will not be an easy fix, as `github.com/blizzy78/varnamelen v0.8.0` dependency is used by golangci-lint, which [sticks to v0.8.0](https://github.com/golangci/golangci-lint/blob/master/go.mod#L22).
We need to refactor the build mechanism a bit. You can raise this at the next [Community Meeting](https://docs.google.com/document/d/1sJQMHbxZdeYJPgAWK1aSt6yzZ4K_8es7woVIrwinVwI/edit?usp=sharing) to discuss this in details.

**Comment by jiriproX** [comment]
Can you please fix this issue by removing that dependency as proposed above? We are still waiting for the fix.

**Comment by adrianchiris** [comment]
#305 solves the issue.
