### ISSUE TITLE
Feature to specify VFs range to SRIOV

### ISSUE THREAD

**Issue by sainath40** [k8snetworkplumbingwg/sriov-cni#270]
## What would you like to be added?

A Feature to specify VFs range so that a VF from the mentioned range will be allocated to the POD.

## What is the use case for this feature / enhancement?

I have 8 vfs that are created from a PF. I want only first 4 vfs to be allocated by SRIOV to my datapath pods. And the remaining 4 vfs (5 to 8 ) to be managed by a user application.

**Comment by SchSeba** [comment]
this is possible using the sriov-operator or with only the sriov-device-plugin.
you can put a range in the request.

**Comment by sainath40** [comment]
I use sriov-device-plugin in my environment, can you share an example on how to do this ?

**Comment by SchSeba** [comment]
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#config-parameters

you can select by the PFname with a range

```
"pfNames": ["netpf0#0,2-7,9"]
```

**Comment by sainath40** [comment]
Thanks @SchSeba , I was able to give VF range using "rootDevices": ["netpf0#0,2-7,9"]
