### ISSUE TITLE
sriov-cni plugin silently throws away issues with LoadConfFromCache

### ISSUE THREAD

**Issue by andreaskaris** [k8snetworkplumbingwg/sriov-cni#275]
### What happened?

sriov-cni plugin silently throws away issues with LoadConfFromCache: https://github.com/k8snetworkplumbingwg/sriov-cni/blob/c44726a013e0b87470151bebe6a87034f181fa95/cmd/sriov/main.go#L201

### What did you expect to happen?

That's on purpose and it makes sense, however, by doing so, we lose insight into valid errors. There should be a logging mechanism to the crio logs (via stderr) which will at least log the failure.

### What are the minimal steps needed to reproduce the bug?

I saw this in a customer environment, I actually don't know how to best reproduce this with minimal steps.

### Anything else we need to know?

I think it'd be nice to have optional debug logging (loglevel and logfile) for the sriov-cni. That would make troubleshooting in the field (e.g. of race conditions) a lot easier.

### Component Versions
Please fill in the below table with the version numbers of applicable components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|SR-IOV Network Device Plugin |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

**Comment by adrianchiris** [comment]
@andreaskaris can we close this one ?

**Comment by andreaskaris** [comment]
of course!
