### ISSUE TITLE
Any plans for cutting a new sriov-cni release?

### ISSUE THREAD

**Issue by missa-wndrvr** [k8snetworkplumbingwg/sriov-cni#299]
## What issue would you like to bring attention to?

Was wondering if there were plans for making a new release for sriov-cni with all the recent bug fixes and features?

**Comment by adrianchiris** [comment]
yes there is. once we get [1]  merged :)

[1] https://github.com/k8snetworkplumbingwg/sriov-cni/pull/298

**Comment by missa-wndrvr** [comment]
And if you don't mind me asking, is there a release date ETA since the code merged :)

**Comment by adrianchiris** [comment]
v2.8.0 release is out.
