### ISSUE TITLE
Support for PFOnly mode and deviceID compatability

### ISSUE THREAD

**Issue by sseetharaman6** [k8snetworkplumbingwg/sriov-cni#97]
I have a use-case of passing PFs directly to pods/VMs and I tested out different CNI options: 
[Upstream SRIOV CNI ](https://github.com/hustcat/sriov-cni/)supports a `pfOnly` option and is functional but is not deviceID aware- so it is hard to use with SRIOV DP.  
[Ehost-device CNI](https://github.com/zshi-redhat/ehost-device-cni) is functional and deviceID aware. It essentially moves the root device identified by the Device plugin into the pod’s namespace and configures IPAM - functionally similar to Intel SR IOV CNI. 
[Intel SRIOV CNI](https://github.com/intel/sriov-cni/) doesn’t support `pfOnly` as yet. https://github.com/intel/sriov-cni/issues/8 was raised previously, but it doesn't quite work.  This is an RFE requesting for this support

**Comment by adrianchiris** [comment]
for the described use-case[ Host device CNI](https://github.com/containernetworking/plugins#main-interface-creating) can be used.
Closing the issue,

if there are further questions please feel free to reopen
